# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dba680efdf84f0c26079713039baea7e235a55449b10e3adb3a9f997dec7b58b7c119ad5dd0f498f2684011547e8132f9bda0579b1f6f084aeebf2e04f573e18

test:
  secret_key_base: a65720602acc9ae0869ab0afb55584a7b28b1a4963538bce44d332e2a824299823a90779f9b19b5b85dae46110eb9ea2702fc56a0cf30b75d8681d1f07bcb215

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
